# Use Node.js 17-alpine as the base image
FROM node:17-alpine

RUN npm install -g nodemon

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install dependencies inside the container
RUN npm install

# Copy the rest of the code into the container
COPY . .

# Expose port 3003 to interact with the app
EXPOSE 3003

# Run the application
CMD ["npm", "start", "dev"]


